apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting-config
  namespace: brownie-metadata
  labels:
    grafana_alerting: "1"
data:
  alerting.yaml: |
    # Grafana Alerting Configuration
    # This file contains notification channels and alert rules for the Brownie Metadata Database
    
    # Notification Channels
    notification_channels:
      - uid: "pagerduty-critical"
        name: "PagerDuty Critical"
        type: "pagerduty"
        settings:
          integrationKey: "${PAGERDUTY_INTEGRATION_KEY}"
          severity: "critical"
          autoResolve: false
        isDefault: false
        sendReminder: true
        frequency: "10m"
        
      - uid: "pagerduty-warning"
        name: "PagerDuty Warning"
        type: "pagerduty"
        settings:
          integrationKey: "${PAGERDUTY_INTEGRATION_KEY}"
          severity: "warning"
          autoResolve: true
        isDefault: false
        sendReminder: true
        frequency: "30m"
        
      - uid: "slack-alerts"
        name: "Slack Alerts"
        type: "slack"
        settings:
          url: "${SLACK_WEBHOOK_URL}"
          channel: "#alerts"
          username: "Brownie Metadata Bot"
          iconEmoji: ":warning:"
          title: "Brownie Metadata Database Alert"
          text: "{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}"
        isDefault: false
        sendReminder: true
        frequency: "15m"
        
      - uid: "email-ops"
        name: "Email Operations Team"
        type: "email"
        settings:
          addresses: "ops@company.com,oncall@company.com"
          subject: "[{{ .Status | toUpper }}] Brownie Metadata Database Alert"
          message: |
            Alert: {{ .AlertName }}
            Status: {{ .Status }}
            {{ range .Alerts }}
            Summary: {{ .Annotations.summary }}
            Description: {{ .Annotations.description }}
            Runbook: {{ .Annotations.runbook_url }}
            {{ end }}
        isDefault: false
        sendReminder: true
        frequency: "1h"
        
      - uid: "teams-alerts"
        name: "Microsoft Teams"
        type: "teams"
        settings:
          url: "${TEAMS_WEBHOOK_URL}"
          title: "Brownie Metadata Database Alert"
          text: "{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}"
        isDefault: false
        sendReminder: true
        frequency: "20m"

    # Alert Rules
    alert_rules:
      - uid: "service-health"
        title: "Service Health Monitoring"
        condition: "C"
        data:
          - refId: "A"
            queryType: ""
            relativeTimeRange:
              from: 600
              to: 0
            datasource:
              type: "prometheus"
              uid: "prometheus"
            model:
              expr: "up{job=\"brownie-metadata-app\"}"
              interval: ""
              legendFormat: ""
              refId: "A"
          - refId: "B"
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasource:
              type: "__expr__"
              uid: "__expr__"
            model:
              conditions:
                - evaluator:
                    params: [0]
                    type: "lt"
                  operator:
                    type: "and"
                  query:
                    params: ["A"]
                    type: "query"
                  reducer:
                    params: []
                    type: "last"
                  type: "query"
              datasource:
                type: "__expr__"
                uid: "__expr__"
              expression: "A"
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: "last"
              refId: "B"
              type: "reduce"
          - refId: "C"
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasource:
              type: "__expr__"
              uid: "__expr__"
            model:
              expression: "B"
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: "C"
              type: "threshold"
        noDataState: "NoData"
        execErrState: "Alerting"
        for: "1m"
        annotations:
          summary: "Brownie Metadata Database service is down"
          description: "The service has been down for more than 1 minute"
          runbook_url: "https://docs.brownie-metadata.com/runbooks/service-down"
        labels:
          severity: "critical"
          service: "brownie-metadata-database"
        notificationSettings:
          receiver: "pagerduty-critical"
          groupBy: ["alertname"]
          groupWait: "10s"
          groupInterval: "10s"
          repeatInterval: "1h"
          
      - uid: "high-error-rate"
        title: "High Error Rate"
        condition: "C"
        data:
          - refId: "A"
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: "prometheus"
              uid: "prometheus"
            model:
              expr: "rate(errors_total[5m]) / rate(requests_total[5m])"
              interval: ""
              legendFormat: ""
              refId: "A"
          - refId: "B"
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasource:
              type: "__expr__"
              uid: "__expr__"
            model:
              conditions:
                - evaluator:
                    params: [0.05]
                    type: "gt"
                  operator:
                    type: "and"
                  query:
                    params: ["A"]
                    type: "query"
                  reducer:
                    params: []
                    type: "last"
                  type: "query"
              datasource:
                type: "__expr__"
                uid: "__expr__"
              expression: "A"
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: "last"
              refId: "B"
              type: "reduce"
          - refId: "C"
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasource:
              type: "__expr__"
              uid: "__expr__"
            model:
              expression: "B"
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: "C"
              type: "threshold"
        noDataState: "NoData"
        execErrState: "Alerting"
        for: "2m"
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for the last 5 minutes"
          runbook_url: "https://docs.brownie-metadata.com/runbooks/high-error-rate"
        labels:
          severity: "warning"
          service: "brownie-metadata-database"
        notificationSettings:
          receiver: "slack-alerts"
          groupBy: ["alertname"]
          groupWait: "10s"
          groupInterval: "10s"
          repeatInterval: "30m"
          
      - uid: "high-response-time"
        title: "High Response Time"
        condition: "C"
        data:
          - refId: "A"
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: "prometheus"
              uid: "prometheus"
            model:
              expr: "histogram_quantile(0.95, rate(request_duration_seconds_bucket[5m]))"
              interval: ""
              legendFormat: ""
              refId: "A"
          - refId: "B"
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasource:
              type: "__expr__"
              uid: "__expr__"
            model:
              conditions:
                - evaluator:
                    params: [2]
                    type: "gt"
                  operator:
                    type: "and"
                  query:
                    params: ["A"]
                    type: "query"
                  reducer:
                    params: []
                    type: "last"
                  type: "query"
              datasource:
                type: "__expr__"
                uid: "__expr__"
              expression: "A"
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: "last"
              refId: "B"
              type: "reduce"
          - refId: "C"
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasource:
              type: "__expr__"
              uid: "__expr__"
            model:
              expression: "B"
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: "C"
              type: "threshold"
        noDataState: "NoData"
        execErrState: "Alerting"
        for: "3m"
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 2 seconds"
          runbook_url: "https://docs.brownie-metadata.com/runbooks/high-response-time"
        labels:
          severity: "warning"
          service: "brownie-metadata-database"
        notificationSettings:
          receiver: "slack-alerts"
          groupBy: ["alertname"]
          groupWait: "10s"
          groupInterval: "10s"
          repeatInterval: "30m"
          
      - uid: "database-issues"
        title: "Database Issues"
        condition: "C"
        data:
          - refId: "A"
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: "prometheus"
              uid: "prometheus"
            model:
              expr: "db_connections_active"
              interval: ""
              legendFormat: ""
              refId: "A"
          - refId: "B"
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasource:
              type: "__expr__"
              uid: "__expr__"
            model:
              conditions:
                - evaluator:
                    params: [80]
                    type: "gt"
                  operator:
                    type: "and"
                  query:
                    params: ["A"]
                    type: "query"
                  reducer:
                    params: []
                    type: "last"
                  type: "query"
              datasource:
                type: "__expr__"
                uid: "__expr__"
              expression: "A"
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: "last"
              refId: "B"
              type: "reduce"
          - refId: "C"
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasource:
              type: "__expr__"
              uid: "__expr__"
            model:
              expression: "B"
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: "C"
              type: "threshold"
        noDataState: "NoData"
        execErrState: "Alerting"
        for: "2m"
        annotations:
          summary: "High database connection count"
          description: "Database has more than 80 active connections"
          runbook_url: "https://docs.brownie-metadata.com/runbooks/high-db-connections"
        labels:
          severity: "warning"
          service: "brownie-metadata-database"
        notificationSettings:
          receiver: "email-ops"
          groupBy: ["alertname"]
          groupWait: "10s"
          groupInterval: "10s"
          repeatInterval: "1h"
