apiVersion: apps/v1
kind: Deployment
metadata:
  name: brownie-metadata-app
  namespace: brownie-metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brownie-metadata-app
  template:
    metadata:
      labels:
        app: brownie-metadata-app
    spec:
      containers:
      - name: app
        image: brownie-metadata-db:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        - containerPort: 8001
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: brownie-metadata-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: brownie-metadata-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: brownie-metadata-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: brownie-metadata-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: brownie-metadata-secrets
              key: postgres-password
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: brownie-metadata-config
              key: LOG_LEVEL
        - name: LOG_FORMAT
          valueFrom:
            configMapKeyRef:
              name: brownie-metadata-config
              key: LOG_FORMAT
        - name: METRICS_ENABLED
          valueFrom:
            configMapKeyRef:
              name: brownie-metadata-config
              key: METRICS_ENABLED
        - name: METRICS_PORT
          valueFrom:
            configMapKeyRef:
              name: brownie-metadata-config
              key: METRICS_PORT
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
      volumes:
      - name: app-logs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: brownie-metadata-app
  namespace: brownie-metadata
spec:
  selector:
    app: brownie-metadata-app
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  - port: 8001
    targetPort: 8001
    name: metrics
  type: ClusterIP

---
# Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brownie-metadata-ingress
  namespace: brownie-metadata
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: brownie-metadata.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: brownie-metadata-app
            port:
              number: 8000
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: brownie-metadata-app
            port:
              number: 8001

---
# HorizontalPodAutoscaler for auto-scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: brownie-metadata-hpa
  namespace: brownie-metadata
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: brownie-metadata-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
