apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brownie-metadata-database.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "brownie-metadata-database.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "brownie-metadata-database.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "brownie-metadata-database.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "brownie-metadata-database.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.app.service.metricsPort }}
              protocol: TCP
          env:
            - name: DB_HOST
              value: {{ .Values.config.dbHost | quote }}
            - name: DB_PORT
              value: {{ .Values.config.dbPort | quote }}
            - name: DB_NAME
              value: {{ .Values.config.dbName | quote }}
            - name: DB_USER
              value: {{ .Values.config.dbUser | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "brownie-metadata-database.fullname" . }}-secrets
                  key: postgres-password
            - name: REDIS_HOST
              value: {{ include "brownie-metadata-database.fullname" . }}-redis
            - name: REDIS_PORT
              value: "6379"
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel | quote }}
            - name: LOG_FORMAT
              value: {{ .Values.config.logFormat | quote }}
            - name: METRICS_ENABLED
              value: {{ .Values.config.metricsEnabled | quote }}
            - name: METRICS_PORT
              value: {{ .Values.config.metricsPort | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          volumeMounts:
            - name: app-logs
              mountPath: /app/logs
      volumes:
        - name: app-logs
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
