apiVersion: v1
kind: Service
metadata:
  name: {{ include "brownie-metadata-database.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "brownie-metadata-database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.app.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "brownie-metadata-database.selectorLabels" . | nindent 4 }}
