name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  # Fast checks for every commit
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install black isort flake8 mypy
    
    - name: Run Black (code formatting)
      run: black --check --diff .
    
    - name: Run isort (import sorting)
      run: isort --check-only --diff .
    
    - name: Run flake8 (linting)
      run: flake8 .
    
    - name: Run mypy (type checking)
      run: mypy src/ --ignore-missing-imports

  # Integration tests (runs on main/PRs)
  integration-tests:
    runs-on: ubuntu-latest
    needs: lint-and-format
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov testcontainers
    
    - name: Run database schema tests
      run: |
        pytest tests/test_integration.py::TestDatabaseSchema -v --tb=short
    
    - name: Run all tests with coverage
      run: |
        pytest tests/ -v --cov=src --cov-report=xml --cov-report=html --disable-warnings
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  # Comprehensive Docker stack integration test
  docker-integration:
    runs-on: ubuntu-latest
    needs: lint-and-format
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest requests
    
    - name: Generate SSL certificates
      run: |
        chmod +x scripts/setup-dev-certs.sh
        ./scripts/setup-dev-certs.sh
        echo "=== Fix certificate ownership for PostgreSQL ==="
        # PostgreSQL needs the key files to be owned by postgres user (999) or root (0)
        sudo chown -R 999:999 dev-certs/ || echo "Could not change ownership, trying alternative..."
        # Alternative: make files readable by postgres user
        chmod 644 dev-certs/*.crt dev-certs/*.key || echo "Could not change permissions"
        ls -la dev-certs/
    
    - name: Run comprehensive Docker integration tests
      run: |
        pytest tests/test_docker_integration.py::TestDockerStackIntegration -v --tb=short --disable-warnings

  # Build and test Docker images
  docker-build:
    runs-on: ubuntu-latest
    needs: lint-and-format
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest requests
    
    - name: Generate SSL certificates
      run: |
        chmod +x scripts/setup-dev-certs.sh
        ./scripts/setup-dev-certs.sh
        echo "=== Fix certificate ownership for PostgreSQL ==="
        # PostgreSQL needs the key files to be owned by postgres user (999) or root (0)
        sudo chown -R 999:999 dev-certs/ || echo "Could not change ownership, trying alternative..."
        # Alternative: make files readable by postgres user
        chmod 644 dev-certs/*.crt dev-certs/*.key || echo "Could not change permissions"
        ls -la dev-certs/
    
    - name: Build database migration image
      run: |
        echo "=== Building database migration image ==="
        docker build -t brownie-metadata-db:test . --progress=plain
        echo "=== Migration image built successfully ==="
    
    - name: Build metrics sidecar image
      run: |
        echo "=== Building metrics sidecar image ==="
        docker build -f Dockerfile.metrics -t brownie-metadata-metrics:test . --progress=plain
        echo "=== Metrics image built successfully ==="
    
    - name: Test Docker Compose stack
      run: |
          echo "=== Pre-startup debugging ==="
          echo "Current directory: $(pwd)"
          echo "Docker version:"
          docker --version
          echo "Docker Compose version:"
          docker compose version
          echo "Certificate files:"
          ls -la dev-certs/
          echo "Certificate file permissions:"
          stat dev-certs/* || echo "No certificate files found"
          echo "Docker Compose config validation:"
          docker compose config
          
          echo "=== Testing PostgreSQL only first ==="
          docker compose up -d postgres || {
            echo "=== PostgreSQL startup FAILED ==="
            echo "=== Exit code: $? ==="
            echo "=== Checking what containers exist ==="
            docker ps -a
          echo "=== Checking PostgreSQL logs ==="
          docker compose logs postgres
          echo "=== Checking PostgreSQL container details ==="
          docker inspect brownie-metadata-postgres
            exit 1
          }
          echo "=== PostgreSQL started successfully ==="
          
          echo "=== Starting all containers ==="
          docker compose up -d 2>&1 || {
            echo "=== Docker compose up FAILED ==="
            echo "=== Exit code: $? ==="
            echo "=== Checking what containers exist ==="
            docker ps -a
            echo "=== Checking docker compose logs ==="
            docker compose logs
            echo "=== Checking individual container logs ==="
            docker compose logs postgres
            docker compose logs redis
            docker compose logs backup
            echo "=== Checking container status ==="
            docker compose ps -a
            exit 1
          }
          echo "=== Docker compose up exit code: $? ==="
          
          echo "=== Immediate container status ==="
          docker compose ps
          
          echo "=== Container status after 5s ==="
          sleep 5
          docker compose ps
          
          echo "=== Container status after 15s ==="
          sleep 10
          docker compose ps
          
          echo "=== Container status after 30s ==="
          sleep 15
          docker compose ps
          
          echo "=== PostgreSQL logs ==="
          docker compose logs postgres
          
          echo "=== Migration logs ==="
          docker compose logs migrate
          
          echo "=== Metrics logs ==="
          docker compose logs metrics-sidecar
          
          echo "=== Backup logs ==="
          docker compose logs backup
          
          echo "=== All container logs ==="
          docker compose logs
          
          echo "=== Container inspection ==="
          docker inspect brownie-metadata-postgres || echo "PostgreSQL container not found"
          
          echo "=== File system check inside PostgreSQL container ==="
          docker exec brownie-metadata-postgres ls -la /var/lib/postgresql/ || echo "Cannot exec into PostgreSQL container"
          
          echo "=== PostgreSQL connection test ==="
          docker exec brownie-metadata-postgres pg_isready -U brownie-fastapi-server -d brownie_metadata || echo "Connection test failed"
          
          docker compose down
    
    - name: Run comprehensive Docker integration tests
      run: |
        pytest tests/test_docker_integration.py::TestDockerStackIntegration -v --tb=short --disable-warnings
